export interface IFavoriteRecipe {
    aggregateLikes: number;
    analyzedInstructions: any[];
    cheap: boolean;
    cookingMinutes: number;
    creditsText: string;
    cuisines: any[];
    dairyFree: boolean;
    diets: any[];
    dishTypes: string[];
    extendedIngredients: any[];
    gaps: string;
    glutenFree: boolean;
    healthScore: number;
    id: number;
    image: string;
    imageType: string;
    instructions: any;
    lowFodmap: boolean;
    occasions: any[];
    originalId: any;
    preparationMinutes: number;
    pricePerServing: number;
    readyInMinutes: number;
    servings: number;
    sourceName: string;
    sourceUrl: string
    spoonacularSourceUrl: string;
    summary: string;
    sustainable: boolean;
    title: string;
    vegan: boolean;
    vegetarian: boolean;
    veryHealthy: boolean;
    veryPopular: boolean;
    weightWatcherSmartPoints: number;
    winePairing: object;
}